### ISSUE TITLE
TypeError: __new__() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by pizycki** [kiwiz/gkeepapi#106]
Please make sure you've done the following before submitting your issue:

- [X] Check that you're running the newest version of the library.
- [X] If you're providing a stack trace, make sure it doesn't contain your password.
- [X] If you're getting a KeyError or ParseException, please follow the instructions [here](https://gkeepapi.readthedocs.io/en/latest/#reporting-errors) to dump the raw data.

Additionally, please provide the following information:

- [X] Operating system
- [X] Python version
---------

I'm just starting with this lib and I'm having the following error while trying to log-in to G Keep.

```
Traceback (most recent call last):
  File "program.py", line 6, in <module>
    success = keep.login(email, pwd)
  File "/home/pawel/.local/lib/python2.7/site-packages/gkeepapi/__init__.py", line 695, in login
    ret = auth.login(username, password, device_id)
  File "/home/pawel/.local/lib/python2.7/site-packages/gkeepapi/__init__.py", line 55, in login
    self._email, password, self._device_id
  File "/home/pawel/.local/lib/python2.7/site-packages/gpsoauth/__init__.py", line 104, in perform_master_login
    return _perform_auth_request(data, proxy)
  File "/home/pawel/.local/lib/python2.7/site-packages/gpsoauth/__init__.py", line 55, in _perform_auth_request
    session.mount(auth_url, AuthHTTPAdapter())
  File "/home/pawel/.local/lib/python2.7/site-packages/requests/adapters.py", line 129, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/home/pawel/.local/lib/python2.7/site-packages/gpsoauth/__init__.py", line 44, in init_poolmanager
    context = SSLContext()
TypeError: __new__() takes at least 2 arguments (1 given)
```

My code 
```
import gkeepapi

keep = gkeepapi.Keep()
email = "xxxxx@gmail.com"
pwd = "xxxxxxxxxxx"
success = keep.login(email, pwd)

note = keep.createNote('Todo', 'Eat breakfast')
keep.sync()
```

My specs:
```
gkeepapi (0.13.4)
python -V: 2.7.17
Ubuntu 18.04 in WSL (Windows Subsystem)
```

I'm just the begginer in Python, so the issue I'm facing here might be trivial and not library specific.
Any help would be nice though :)

**Comment by pizycki** [comment]
Okay, found out that this issue is related to #105 (sorry, for duplicate)

Got it working with downgrading 
```
pip install --upgrade gpsoauth==0.4.2
```
and used Google App Password to authenticate

Closing :)
