### ISSUE TITLE
gkeepapi.APIException

### ISSUE THREAD

**Issue by aFrankLion** [kiwiz/gkeepapi#15]
I am receiving the following APIException on multiple computers after being able to log in and use the API earlier today. I am able to successfully login using Google App passwords, but the error seems to occur during the initial sync.

Using Python 3.6.3 and gkeepapi-0.10.2:

```python
import gkeepapi
keep = gkeepapi.Keep()
login_success = keep.login(my_username, my_app_password)
```
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): android.clients.google.com
DEBUG:urllib3.connectionpool:https://android.clients.google.com:443 "POST /auth HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): android.clients.google.com
DEBUG:urllib3.connectionpool:https://android.clients.google.com:443 "POST /auth HTTP/1.1" 200 None
DEBUG:keep:Starting sync: None
DEBUG:keep:Syncing 0 labels and 0 nodes
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "POST /notes/v1/changes HTTP/1.1" 400 None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\gkeepapi\__init__.py", line 347, in login
    self.sync()
  File "C:\Anaconda3\lib\site-packages\gkeepapi\__init__.py", line 543, in sync
    labels=[i.save() for i in self._labels.values()] if labels_updated else None,
  File "C:\Anaconda3\lib\site-packages\gkeepapi\__init__.py", line 249, in changes
    json=params
  File "C:\Anaconda3\lib\site-packages\gkeepapi\__init__.py", line 173, in send
    raise APIException(error['code'], error)
gkeepapi.APIException: {'errors': [{'domain': 'global', 'reason': 'invalid', 'message': 'Invalid Value'}], 'code': 400, 'message': 'Invalid Value'}
```

**Comment by aFrankLion** [comment]
I have been able to reproduce this behavior using two different Google accounts that have no shared lists, so the problem does not _seem_ to be related to the content being synced.

**Comment by sentriz** [comment]
exact same issue here

**Comment by sentriz** [comment]
I've been trying to debug this. It looks like the request made here https://github.com/kiwiz/gkeepapi/blob/master/gkeepapi/__init__.py#L246
needs some more keys, this is the minimum shape I could get away with
```json
{
    "clientTimestamp": "2018-03-03T19:06:34.761Z",
    "nodes": [],
    "requestHeader": {
        "clientVersion": {
            "major": "3",
            "minor": "2",
            "build": "9",
            "revision": "4"
        },
        "clientPlatform": "WEB",
        "capabilities": [
            {
                "type": "EC"
            },
            {
                "type": "TR"
            },
            {
                "type": "SH"
            },
            {
                "type": "LB"
            },
            {
                "type": "RB"
            },
            {
                "type": "DR"
            },
            {
                "type": "AN"
            },
            {
                "type": "PI"
            },
            {
                "type": "EX"
            },
            {
                "type": "SNB"
            },
            {
                "type": "CO"
            },
            {
                "type": "MI"
            },
            {
                "type": "NC"
            }
        ],
        "clientSessionId": "s--numbersnumbers-numbers"
    }
}
```

so removing any of `clientPlatform`, `clientVersion`, `clientTimestamp`, and `clientLocale` would give the 400 we're talking about. 
I have no idea how do add the likes of `clientSessionId` though

**Comment by aFrankLion** [comment]
@sentriz, as you suggested, by adding `clientTimestamp`, `clientVersion`, `clientPlatform`, and `clientSessionId` I am also able to login and sync my Keep data.

**Comment by aFrankLion** [comment]
@sentriz, aside from `clientTimeStamp`, no, I haven't been able to get a full solution yet. The value for `clientSessionId` doesn't seem to impede function if set arbitrarily. Acceptable values for `clientVersion` and `clientPlatform` seem more restrictive.

**Comment by kiwiz** [comment]
Thanks for the investigative work @aFrankLion @sentriz. I've pushed up a fix for the issue - let me know if it works for you.

**Comment by aFrankLion** [comment]
@kiwiz, your latest commits have restored functionality for me. Thanks!

**Comment by sentriz** [comment]
@kiwiz, same here, thank you :)
