### ISSUE TITLE
gkeepapi.LoginException: NeedsBrowser

### ISSUE THREAD

**Issue by EcmaXp** [kiwiz/gkeepapi#20]
```C:\Users\EcmaXp>python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gkeepapi
>>> import getpass
>>> gkeepapi.Keep()
<gkeepapi.Keep object at 0x000001B86923C438>
>>> keep = _
>>> keep.login("********@********", getpass.getpass())
Password:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\EcmaXp\AppData\Roaming\Python\Python36\site-packages\gkeepapi\__init__.py", line 363, in login
    ret = auth.login(username, password, get_mac())
  File "C:\Users\EcmaXp\AppData\Roaming\Python\Python36\site-packages\gkeepapi\__init__.py", line 67, in login
    raise LoginException(res.get('Error'), res.get('ErrorDetail'))
gkeepapi.LoginException: ('NeedsBrowser', 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')```

**Comment by EcmaXp** [comment]
Note. I setup the OTP for secure.

**Comment by sentriz** [comment]
can you use an [app pass](https://myaccount.google.com/apppasswords) if getpass() isn't already?

**Comment by EcmaXp** [comment]
success. thanks!

**Comment by kiwiz** [comment]
Added a note to the readme for now.

**Comment by hannesfrank** [comment]
I don't have 2-factor enabled but still get the error. This means also there is no option for me to create an app password. Any suggestions?

**Comment by hannesfrank** [comment]
Bad news, the unlock captcha setting appears to be a one thim thing: It works only for the next login attempt. Today I get the same NeedsBrowser error again.

Could be that setting up 2-factor and using an app password is the only reliable solution, but I don't want to use that.

Another possibility would be to try parsing the Website. [`gmusicapi` implements a `Webclient`](https://github.com/simon-weber/gmusicapi/blob/develop/gmusicapi/session.py#L94) which uses `mechanicalsoup`. I haven't testet that though.

But if someone figures out a reliable solution, I'd be happy to make a PR. 😃

**Comment by dufferzafar** [comment]
Facing the same `NeedsBrowser` issue. Was so excited to try this. :cry: 

@hannesfrank That gmusicapi approach looks decent to me. I'll test it out, and report. If it works, we would be okay with adding this here, right?

A bit unrelated question, but are the keep notes stored on disk somewhere? or are they only in memory?

**Comment by buyuk-dev** [comment]
I experienced this issue myself when i was trying to test out gkeepapi. Funny thing is, I had disabled two-step authentication and the issue still occurred. So I thought what would happen if I enable two step authentication for my google account to be able to generate app password for my script. It turns out that it worked that way :) Hope this helps someone.

**Comment by wahlfeld** [comment]
Hey guys, I'm getting this `LoginException: NeedsBrowser` error even though I'm using an app password. This seems to have started happening within the last week. Here's my code:

```print('importing modules')
import gkeepapi
import os

print('setting environment variables')
user = os.environ['GKEEP_USERNAME']
pw = os.environ['GKEEP_APP_PASSWORD']

print('logging into Keep')
keep = gkeepapi.Keep()
keep.login(user, pw)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/gkeepapi/__init__.py", line 470, in login
    ret = auth.login(username, password, get_mac())
  File "/Library/Python/2.7/site-packages/gkeepapi/__init__.py", line 48, in login
    raise exception.LoginException(res.get('Error'), res.get('ErrorDetail'))
gkeepapi.exception.LoginException: (u'NeedsBrowser', u'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')```

<img width="1440" alt="screen shot 2018-10-16 at 1 17 20 pm" src="https://user-images.githubusercontent.com/24707819/46988753-db7ab200-d145-11e8-98f7-36ce92923169.png">

**Comment by geoffcline** [comment]
I'm only getting 'NeedsBrowser' when requesting from heroku/aws. I am able to use app password on home or work isp (att). Exact same code. Maybe this is required when google doesn't recognize the device?

**Comment by kiwiz** [comment]
Can someone test the following code snippet with the information generated from the browser flow?

```python
import google_auth_oauthlib.flow

auth = google_auth_oauthlib.flow.Flow.from_client_config(
	{'installed': {
		'auth_uri': None,
		'token_uri': None,
		'client_id': CLIENT_ID,
	}},
	['https://www.google.com/accounts/OAuthLogin']
)

auth.fetch_token(code=OAUTH_CODE)
# Hopefully no exception was thrown
```

**Comment by MortimerMcMire315** [comment]
Hi @kiwiz ,

It looks like a couple more pieces are needed, and the scope URL you have there looks invalid. Here's what worked for me:

```
from google_auth_oauthlib.flow import Flow     
                                                                                                                                                                                                                                                                                                     
client_cfg = {'installed': {                                                                                                                                             
               'auth_uri' : 'https://accounts.google.com/o/oauth2/auth',                                                                                                  
               'token_uri' : 'https://oauth2.googleapis.com/token',                                                                                                       
               'client_id' : MY_CLIENT_ID,                                                                                 
               'client_secret' : MY_CLIENT_SECRET,                                                                                                                             }}               
                                                                                                                                          
scopes = ['https://www.googleapis.com/auth/userinfo.email', 'https://www.googleapis.com/auth/userinfo.profile']                                                           
redir_uri = 'urn:ietf:wg:oauth:2.0:oob'                                                                                                                                   
                                                                                                                                                                          
auth = Flow.from_client_config(client_cfg, scopes, redirect_uri=redir_uri)                                                                                                 
print(auth.authorization_url(prompt='consent'))

# Here, I went to the printed URL and consented to obtain OAUTH_CODE
                                                                                                                    
auth.fetch_token(code=OAUTH_CODE)
```

**Comment by stellarpower** [comment]
I get the NeedsBrowser error when I try and login from my server, where annoyingly I have no browser. But on my laptop everything runs fine. In fact Google logged something along the way as a critical security error and I had to reset my passwords. I don't have two-factor authentication on and back in the day I ticked the 'allow less secure apps' option.

**Comment by kiwiz** [comment]
@MortimerMcMire315 Thanks for looking into this. I've been unable to repro, but I believe those parameters are correct. We're trying to replicate the parameters described in the second [post](https://github.com/kiwiz/gkeepapi/issues/20#issuecomment-374275380).

**Comment by manu354** [comment]
Same problem _just_ started happening to me. It was working yesterday. 

My guess is that it may have something to do with changing internet connections? 

The only code I am using is:

```
import gkeepapi
keepAPI = gkeepapi.Keep()
succ = keepAPI.login('####', '###')
```
Throws error:
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    succ = keepAPI.login('#####@gmail.com', '#######')
  File "/home/######/.local/lib/python3.5/site-packages/gkeepapi/__init__.py", line 470, in login
    ret = auth.login(username, password, get_mac())
  File "/home/#####/.local/lib/python3.5/site-packages/gkeepapi/__init__.py", line 48, in login
    raise exception.LoginException(res.get('Error'), res.get('ErrorDetail'))
gkeepapi.exception.LoginException: ('NeedsBrowser', 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')
```

**Comment by dkdndes** [comment]
You need to allow an application to be added via this URL, it will simulate the recaptcha check:

* https://accounts.google.com/DisplayUnlockCaptcha

**Comment by pabloariasal** [comment]
Is there any resolution or update on this? I'm experiencing the same problem. DisplayUnlockCaptcha works partially. The error appears again after a while. 2-Step verification saddly isn't an option for me right now. Is there something else I should try or test?

**Comment by kiwiz** [comment]
Nothing concrete, unfortunately. The last few comments here might be useful: https://github.com/kiwiz/gkeepapi/issues/69

**Comment by zaimramlan** [comment]
> You need to allow an application to be added via this URL, it will simulate the recaptcha check:
> 
> * https://accounts.google.com/DisplayUnlockCaptcha
> 
> gkeepapi and the packaged used for the Android Application settings don't support recaptcha, and that's how google blocks you initially.

This was what worked for me. I'm using a test account with no 2FA mechanism enabled in case anyone was wondering.
