### ISSUE TITLE
KeyError: 'isArchived' until all old items are archived

### ISSUE THREAD

**Issue by OriginalTestUzer** [kiwiz/gkeepapi#5]
Throws a KeyError: 'isArchived' error until all old items are archived. Items can be unarchived afterwards with no error. Needs an invalid value check on key.

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    keep.sync()
  File "......\gkeepapi\__init__.py", line 460, in sync
    self._parseNodes(changes['nodes'])
  File "......\gkeepapi\__init__.py", line 484, in _parseNodes
    node = _node.from_json(raw_node)
  File "......\gkeepapi\node.py", line 44, in from_json
    node.load(raw)
  File "......\gkeepapi\node.py", line 1345, in load
    self._load(raw) # pylint: disable=protected-access
  File "......\gkeepapi\node.py", line 959, in load
    self._archived = raw['isArchived']
KeyError: 'isArchived'

**Comment by kiwiz** [comment]
By old, do you mean keep notes that were created a long time ago (possibly before archiving was a thing)?
