### ISSUE TITLE
Parse error when logging in

### ISSUE THREAD

**Issue by jossafossa** [kiwiz/gkeepapi#54]
I get an error when logging in with `keep.login('[username]', '[password]')`

**gkeepapi.exception.ParseException**
```
{'drawingId': 'd2af9979-a5d0-40a3-89d8-99717c251aad',
 'snapshotData': {'byte_size': 13686,
                  'extracted_text': '',
                  'extraction_status': 'SUCCEEDED',
                  'height': 2048,
                  'is_uploaded': True,
                  'kind': 'notes#blob',
                  'mimetype': 'image/png',
                  'type': 'IMAGE',
                  'width': 1316},
 'snapshotFingerprint': '4439851323553804410',
 'snapshotProtoFprint': '4439851323553804410',
 'thumbnailGeneratedTime': '2018-06-27T15:51:11.827Z'}
```

**Full traceback**
```
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\gkeepapi\node.py", line 196, in load
    self._load(raw)
  File "C:\Python35\lib\site-packages\gkeepapi\node.py", line 1567, in _load
    self._ink_hash = raw['inkHash']
KeyError: 'inkHash'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/STACK/Experiments/random/googlekeep/main.py", line 14, in <module>
    keep.login('[username]', '[password]')
  File "C:\Python35\lib\site-packages\gkeepapi\__init__.py", line 472, in login
    self.load(auth, state, sync)
  File "C:\Python35\lib\site-packages\gkeepapi\__init__.py", line 517, in load
    self.sync(True)
  File "C:\Python35\lib\site-packages\gkeepapi\__init__.py", line 777, in sync
    self._parseNodes(changes['nodes'])
  File "C:\Python35\lib\site-packages\gkeepapi\__init__.py", line 806, in _parseNodes
    node = _node.from_json(raw_node)
  File "C:\Python35\lib\site-packages\gkeepapi\node.py", line 1723, in from_json
    node.load(raw)
  File "C:\Python35\lib\site-packages\gkeepapi\node.py", line 196, in load
    self._load(raw)
  File "C:\Python35\lib\site-packages\gkeepapi\node.py", line 1621, in _load
    self.blob = self.from_json(raw.get('blob'))
  File "C:\Python35\lib\site-packages\gkeepapi\node.py", line 1615, in from_json
    blob.load(raw)
  File "C:\Python35\lib\site-packages\gkeepapi\node.py", line 196, in load
    self._load(raw)
  File "C:\Python35\lib\site-packages\gkeepapi\node.py", line 1541, in _load
    self._drawing_info.load(raw['drawingInfo'])
  File "C:\Python35\lib\site-packages\gkeepapi\node.py", line 198, in load
    raise_from(exception.ParseException('Parse error in %s' % (type(self)), raw), e)
  File "C:\Python35\lib\site-packages\future\utils\__init__.py", line 400, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
gkeepapi.exception.ParseException: Parse error in <class 'gkeepapi.node.NodeDrawingInfo'>
```

**Comment by jossafossa** [comment]
commit https://github.com/kiwiz/gkeepapi/pull/53/commits/0cc687862679195d5634dba3421805404e6d7896 fixed my issue.
