### ISSUE TITLE
Can't login anymore?

### ISSUE THREAD

**Issue by 2hands10fingers** [kiwiz/gkeepapi#6]
```
Traceback (most recent call last):
  File "gkeep.py", line 13, in <module>
    keep.sync()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gkeepapi/__init__.py", line 449, in sync
    labels=[i.save() for i in self._labels.values()] if labels_updated else None,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gkeepapi/__init__.py", line 211, in changes
    json=params
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gkeepapi/__init__.py", line 131, in send
    raise LoginException('Not logged in')
gkeepapi.LoginException: Not logged in
```

I haven't changed my code since last night.

**Comment by kiwiz** [comment]
I've updated the code to show the exact error from the servers. Try updating and checking again.

**Comment by 2hands10fingers** [comment]
I updated it. I got this error
```
Traceback (most recent call last):
  File "gkeep.py", line 9, in <module>
    keep.login('andalltheworldisgreen', 'max321321')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gkeepapi/__init__.py", line 263, in login
    return self._api.login(username, password, get_mac())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gkeepapi/__init__.py", line 71, in login
    raise LoginException(res.get('Error'), res.get('ErrorDetail'))
gkeepapi.LoginException: ('NeedsBrowser', 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')
```

**Comment by 2hands10fingers** [comment]
It works now. Apparently it doesn't like if I use variables to insert my login information.
