### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'save'

### ISSUE THREAD

**Issue by funktionzero** [kiwiz/gkeepapi#62]
Here's more fun for you. See what happens when I call `keep.dump()`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/__init__.py", line 583, in dump
    'nodes': [node.save(False) for node in nodes]
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/node.py", line 1738, in save
    ret['blob'] = self.blob.save(clean)
AttributeError: 'NoneType' object has no attribute 'save'
```
Let me know if I can help you further.

**Comment by kiwiz** [comment]
@funktionzero It looks like a blob isn't being initialized correctly. Do you see any other warnings/errors with `DEBUG` on? If you're up to patching the source, I'd be interested in seeing if `raw` is ever `None` [here](https://github.com/kiwiz/gkeepapi/blob/master/gkeepapi/node.py#L1715). If so, could you check which Note has that blob and whether anything seems off about it?

**Comment by funktionzero** [comment]
I added some crude logging to node.py, including a print statement after line 1715. I never observe 'raw' being None there. Judging by what gets printed at the start of every `save(...)` function, the troublesome blob seems to be the first encountered child of a note node which has 11 photos attached (and itself contains text with math symbols, but I can retrieve and read it correctly).

If I set `DEBUG = True`, the error happens earlier during login with the following stack trace:
```
Traceback (most recent call last):
  File "keep.py", line 8, in <module>
    keep.login('...', '...')
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/__init__.py", line 519, in login
    self.load(auth, state, sync)
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/__init__.py", line 565, in load
    self.sync(True)
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/__init__.py", line 838, in sync
    self._parseNodes(changes['nodes'])
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/__init__.py", line 868, in _parseNodes
    node = _node.from_json(raw_node)
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/node.py", line 1840, in from_json
    node.load(raw)
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/node.py", line 213, in load
    self._load(raw)
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/node.py", line 1737, in _load
    super(Blob, self)._load(raw)
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/node.py", line 1848, in _load
    self._find_discrepancies(raw) # pylint: disable=protected-access
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/node.py", line 174, in _find_discrepancies
    s_raw = self.save(False)
  File "/home/funktionzero/.local/lib/python2.7/site-packages/gkeepapi/node.py", line 1742, in save
    ret['blob'] = self.blob.save(clean)
AttributeError: 'NoneType' object has no attribute 'save'
```

**Comment by funktionzero** [comment]
A snapshot of the empty Blob object taken inside the save(...) method:

![blob type none](https://user-images.githubusercontent.com/21251776/63229968-c60f6200-c206-11e9-9fec-44e9c471f06b.png)

(I did not manage to jsonify nor pickle it without taking the whole state with it)

The parent note has 14 children: 2 empty blobs, 11 NodeImage blobs, 1 ListItem. I don't know what the empty blobs might represent, as the website and the app only show 11 pictures plus text body. I think they may be safe to ignore.

I can also confirm that `raw` is never `None` as the debugger never stops there before this point.

**Comment by funktionzero** [comment]
It turns out that the node causing this is the one already seen in https://github.com/kiwiz/gkeepapi/issues/42#issuecomment-522339052 from the other issue closed earlier.

**Comment by kiwiz** [comment]
@funktionzero Thanks for the additional debugging info! Just to clarify, it's still an issue since the #42 fix?

**Comment by funktionzero** [comment]
Yes.

**Comment by kiwiz** [comment]
@funktionzero Pushed out a (comically simple) fix for the issue. Can you confirm if the issue is fixed?

**Comment by funktionzero** [comment]
I can confirm. Tested with dump() and subsequent restore().

By the way, that's the same workaround I've used in the meantime. I thought a proper solution would be to drop the Blob node at parsing time if its .blob is null. But hey, if it's this simple, all the better.

Many thanks.

**Comment by kiwiz** [comment]
Ack, thanks for testing.

That's a valid option too. In my testing, it doesn't matter what we send back for `Blob` entries, because they appear to be immutable. This change just maps to the source data better.
