### ISSUE TITLE
KeyError: u'##################'

### ISSUE THREAD

**Issue by Cajet0** [kiwiz/gkeepapi#64]
I'm using an app password but now I get this error:

```
Traceback (most recent call last):
  File "collect_data.py", line 5, in <module>
    success = keep.login('email', 'app_password')
  File "/Library/Python/2.7/site-packages/gkeepapi/__init__.py", line 519, in login
    self.load(auth, state, sync)
  File "/Library/Python/2.7/site-packages/gkeepapi/__init__.py", line 565, in load
    self.sync(True)
  File "/Library/Python/2.7/site-packages/gkeepapi/__init__.py", line 838, in sync
    self._parseNodes(changes['nodes'])
  File "/Library/Python/2.7/site-packages/gkeepapi/__init__.py", line 891, in _parseNodes
    self._nodes[curr].indent(node, False)
KeyError: u'number&letters-number-number-number-numbers&letters'
```

replace 'number' & 'numbers&letters' for number and letters, seems like a private/public key or something.

**Comment by Cajet0** [comment]
I do not know what this line does but I just commented it and it worked.
```
#if curr is not None:
                #self._nodes[curr].indent(node, False)
```

**Comment by kiwiz** [comment]
Hi, does this still happen on the newest version (without patches)?

**Comment by Cajet0** [comment]
Don't know man. I stopped gkeepapi.

**Comment by kiwiz** [comment]
Ack, thanks for the resp. Closing this issue.
