### ISSUE TITLE
JSONDecodeError 404 when logging in with 0.12.0.

### ISSUE THREAD

**Issue by wizpig64** [kiwiz/gkeepapi#93]
With gkeepapi 0.12.0, I can't log in with Keep().resume().

Re-installing 0.11.16 allowed my script to run again.
Deleting my old session.json did not help.

```
$ python --version
Python 3.8.4
$ python my_script.py
[00:00:00.294899] [INFO] Resuming session...
<Response [404]>
Traceback (most recent call last):
  File "my_script.py", line 69, in login_or_resume
    return keep.resume(USER, master_token, state=state)
  File "/home/phillip/.pyenv/versions/keep/lib/python3.8/site-packages/gkeepapi/__init__.py", line 716, in resume
    self.load(auth, state, sync)
  File "/home/phillip/.pyenv/versions/keep/lib/python3.8/site-packages/gkeepapi/__init__.py", line 743, in load
    self.sync(True)
  File "/home/phillip/.pyenv/versions/keep/lib/python3.8/site-packages/gkeepapi/__init__.py", line 995, in sync
    self._sync_reminders(resync)
  File "/home/phillip/.pyenv/versions/keep/lib/python3.8/site-packages/gkeepapi/__init__.py", line 1005, in _sync_reminders
    changes = self._reminders_api.list()
  File "/home/phillip/.pyenv/versions/keep/lib/python3.8/site-packages/gkeepapi/__init__.py", line 594, in list
    return self.send(
  File "/home/phillip/.pyenv/versions/keep/lib/python3.8/site-packages/gkeepapi/__init__.py", line 223, in send
    response = response.json()
  File "/home/phillip/.pyenv/versions/keep/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/phillip/.pyenv/versions/3.8.4/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/phillip/.pyenv/versions/3.8.4/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/phillip/.pyenv/versions/3.8.4/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kiwiz** [comment]
Looks like I had some debug code active. `0.12.1` should fix the problem.

**Comment by wizpig64** [comment]
that fixed this issue, thanks.
